# Generated by Django 5.2 on 2026-09-09 09:47

from django.db import migrations


def create_experience(apps, schema_editor):
    Experience = apps.get_model("main", "Experience")

    Experience.objects.get_or_create(
        title="Staff BEM Fasilkom UI - Departemen Olahraga",
        defaults={
            "description": "Staff BEM Fasilkom UI pada Departemen Olahraga.",
            "category": "full-time",
            "thumbnail": None,
            "ended_at": None,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_project"),
    ]

    operations = [
        migrations.RunPython(create_experience),
    ]